name: app_network
description: app network
version: 0.0.2

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: 5.4.3+1

  local_storage:
    path: ../local_storage

#  graphql: 5.1.3

dev_dependencies:
  app_linter:
    path: ../app_linter
  mockito: 5.4.2
  build_runner: 2.4.10
  test: 1.24.9
  flutter_mock_web_server: 1.0.0
