name: local_storage
description: local storage of application
version: 0.0.2

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: 2.1.1
  flutter_secure_storage: 8.0.0

dev_dependencies:
  app_linter:
    path: ../app_linter
  mockito: 5.4.2
  build_runner: 2.4.10
  test: 1.24.9
